- New package for asterisk 1.8. Not selected for build in any target (won't build using uclibc because of undefined reference to "uselocale", works building with glibc).